services:
  payment_service_mongodb:
    image: mongo:7.0
    container_name: payment-service-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: payment-service-db-user
      MONGO_INITDB_ROOT_PASSWORD: dbinitPASSWORD001axi00
      MONGO_INITDB_DATABASE: payment-service-db
    volumes:
      - payment_mongodb_data:/data/db
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  payment-service:
    build: .
    container_name: payment_service
    restart: unless-stopped
    depends_on:
      payment_service_mongodb:
        condition: service_started
    ports:
      - '8090:8090'
    volumes:
      - ./Config.toml:/app/Config.toml
      - ./logs:/app/logs
      - ./public.crt:/app/public.crt
    environment:
      BAL_CONFIG_FILES: /app/Config.toml
    healthcheck:
      test:
        ['CMD', 'curl', '-f', 'http://localhost:8090/payment-service/health']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  payment_mongodb_data:
  payment_service_logs:
