services:
  payment_service_mongodb:
    image: mongo:7.0
    container_name: payment-service-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: payment-service-db-user
      MONGO_INITDB_ROOT_PASSWORD: dbinitPASSWORD001axi00
      MONGO_INITDB_DATABASE: payment-service-db
    volumes:
      - payment_mongodb_data:/data/db
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  payment-service:
    build: .
    container_name: payment_service
    image: payment-service-payment-service:latest
    restart: unless-stopped
    depends_on:
      payment_service_mongodb:
        condition: service_started
      kafka:
        condition: service_started
    ports:
      - '9091:9091'
    volumes:
      - ./Config.toml:/app/Config.toml
      - ./logs:/app/logs
      - ./public.crt:/app/public.crt
    environment:
      BAL_CONFIG_FILES: /app/Config.toml

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka_server
    restart: always
    ports:
      - '9094:9094'
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  payment_mongodb_data:
  payment_service_logs:
  kafka_data:
  zookeeper_data:
  kafka_logs:
